### ISSUE TITLE
OpenIRT load failed on VS2015

### ISSUE THREAD

**Issue by Hao-HUST** [sglab/OpenIRT#1]
Hi, thanks for sharing your work.

I imported the OpenIRT_src.sln into VS2015, but the OpenIRT load failed. Any suggestions?
![image](https://user-images.githubusercontent.com/10823967/47565794-32f5fa80-d95c-11e8-9025-fc9688473324.png)

**Comment by sgvrlab** [comment]
Thank you for letting me know this issue.

Unfortunately, it requires to edit the file "PROJECT/OpenIRT/OpenIRT.vcxproj" manually.

Follow the instructions:
1. Change all the value of "PlatformToolset" to yours: 
v100 -> v120(VS2013), v140(VS2015) or v141(VS2017)
![solution1](https://user-images.githubusercontent.com/10989232/47910476-5843b500-ded6-11e8-967e-e181843586d4.PNG)

2. Change the CUDA version to yours.
![solution2](https://user-images.githubusercontent.com/10989232/47910504-727d9300-ded6-11e8-8c20-a6bb6b501629.PNG)
![solution3](https://user-images.githubusercontent.com/10989232/47910509-74dfed00-ded6-11e8-8e76-2b2672b31673.PNG)

Thanks.

**Comment by sgvrlab** [comment]
I loaded the project successfully but found some compilation errors in the recent environment.

I will open a new issue about the error and discuss it there.
